import json
import logging
from typing import Any, Dict
from app.agents.base_agent import BaseAgent
from app.ai.prompts.review_prompts import (
    DEBUGGER_JSON_SCHEMA,
    DEBUGGER_SYSTEM_INSTRUCTION,
    DEBUGGER_USER_PROMPT,
)

logger = logging.getLogger("codeguru")


class DebuggerAgent(BaseAgent):
    """Agent that performs compile-check reviews detecting runtime, syntax, or logic bugs."""

    async def debug_code(self, code: str, language: str) -> Dict[str, Any]:
        """Orchestrate bug detection execution by formatting inputs, executing LLM, and parsing JSON."""
        system_instruction, _ = await self.prompt_service.get_prompt(self.db, "debugger_system")
        user_prompt_tpl, _ = await self.prompt_service.get_prompt(self.db, "debugger_user")
        prompt = user_prompt_tpl.format(language=language, code=code)

        try:
            raw_response = await self._call_llm(
                prompt=prompt,
                system_instruction=system_instruction,
                schema=DEBUGGER_JSON_SCHEMA,
                complexity="complex"
            )

            # Ensure any markdown wraps generated by fallback LLMs are cleaned
            cleaned_response = raw_response.strip()
            if cleaned_response.startswith("```json"):
                cleaned_response = cleaned_response[7:]
            if cleaned_response.endswith("```"):
                cleaned_response = cleaned_response[:-3]
            cleaned_response = cleaned_response.strip()

            parsed = json.loads(cleaned_response)

            # Validate structural contract
            required_keys = ["has_bugs", "bugs"]
            for key in required_keys:
                if key not in parsed:
                    raise KeyError(f"Missing required key in debugger report: {key}")

            return parsed
        except Exception as e:
            logger.error(f"DebuggerAgent failed to process or parse response: {str(e)}", exc_info=True)
            return {
                "has_bugs": False,
                "bugs": []
            }
