import json
import logging
from typing import Any, Dict
from app.agents.base_agent import BaseAgent
from app.ai.prompts.review_prompts import (
    REVIEWER_JSON_SCHEMA,
    REVIEWER_SYSTEM_INSTRUCTION,
    REVIEWER_USER_PROMPT,
)

logger = logging.getLogger("codeguru")


class ReviewerAgent(BaseAgent):
    """Agent that performs structured reviews checking readability, style, security, and complexity."""

    async def review_code(self, code: str, language: str) -> Dict[str, Any]:
        """Orchestrate code review execution by formatting inputs, executing LLM, and parsing JSON."""
        system_instruction, _ = await self.prompt_service.get_prompt(self.db, "reviewer_system")
        user_prompt_tpl, _ = await self.prompt_service.get_prompt(self.db, "reviewer_user")
        prompt = user_prompt_tpl.format(language=language, code=code)
        
        try:
            raw_response = await self._call_llm(
                prompt=prompt,
                system_instruction=system_instruction,
                schema=REVIEWER_JSON_SCHEMA,
                complexity="complex"
            )
            
            # Ensure any markdown wraps generated by fallback LLMs are cleaned
            cleaned_response = raw_response.strip()
            if cleaned_response.startswith("```json"):
                cleaned_response = cleaned_response[7:]
            if cleaned_response.endswith("```"):
                cleaned_response = cleaned_response[:-3]
            cleaned_response = cleaned_response.strip()
            
            parsed = json.loads(cleaned_response)
            
            # Perform basic validation to guarantee keys exist
            required_keys = ["score", "summary", "issues", "refactored_code"]
            for key in required_keys:
                if key not in parsed:
                    raise KeyError(f"Missing required key in review report: {key}")
                    
            return parsed
        except Exception as e:
            logger.error(f"ReviewerAgent failed to process or parse response: {str(e)}", exc_info=True)
            return {
                "score": 0,
                "summary": f"Failed to complete code review analysis: {str(e)}",
                "issues": [
                    {
                        "category": "style",
                        "line": 1,
                        "description": "The AI model output could not be parsed successfully.",
                        "suggestion": "Check code formatting and retry."
                    }
                ],
                "refactored_code": code
            }
